---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBB9xL4PeaQKzi6igLBcm0e0dXVPruBOi+hD84Qogj1YWv81ezf9o3reheECoxo7ibHIPEyDWld1Z3ZklKB7EjKXgmb+qMYey4D/7LuiVMvn7MVdkTFNXCjTWk2Dwz8uIjmLROqEZFoBW3Lx8VJKLS0pAQJdVUMac7ubfbknnuGYZDEQE9LHO//WTX7oXTRkefYQE1XVQeDwC3lkjSKxbubWyyUopu2cGVuG9L/GpE6gs1kCpk6gyse21/VskvQs79SkWJwX2OZKSlygwmxtyWEU4V5b6pPZc04wU0+ymtRLbpjpglDvN4GagqnG6hZoBsnu1WMLsOetGz7leDSBytNhTH61JC+IuhRgcKGD4fJl0MAhfLvdg0Ebwcz3qMpxAlyDpKAkDcP5za+xgIq5MgqDAugF9Gq9kdMQvqbZD4i4DZtqHJRm+KEfgxHjhdcFKN0aFUmab/IkDKyrC19QviMlII1kKGBrybZHUZCgo/PWUGwOC0374Lo/zNI38gRNQO27ZpFh9jd3T5h9WNyhsY++fEyQ0B89fMxblQyRw940nrqyCqf9JADatnVLOXzdd0cdAlIvVYJCzoGQpg7ySLcaKfjWvomZwnBwPK3xX5T0qnozf1fKDJRFcz+zJ0s6mmWUqPD6Ohx0fNzw5rMafM8jQSXJTPagCzbV92pxQKDZvIczj9wCoTNRPEmNBKctn5mt5sMtHyh
    admin-user: AgB2DKYy9tNRbVjbqjVbz82UU3v3wGulHohZvTh3KTycpCx6+urBSrKDz9b24YFX1+krurOkc9Vl0BtsGlXI0s5N3c0s8O40nziZclLL1qSKO4WEg1i12wTuOkwXH0OaZP3PiublCk9dOZFRQJVvXnhfzxoLttQskWQ0ut80S/sGtsLHgWfDFyShndONaEi62hAxr+RuGGOj//h0zB0CAF02ZYuI4AYD4lOA9DbMWOCwKxoNEX2HOinXswMfMapf89u8I0ZWcPklwQnOO87O6c9NuG3tKPRaQMBWhUMeCnVKolqAOMDgtLBI3oGh3TPdOxhVdvcT1pABjURLCGf82QDqEzw7Db/pMRCGr8lEJvH3d6BgcpnXmlj9NHGMV+7uwG23gaO42QoA73C84YUnMU/Zij67Z3W6yBSP9Rtb7W9vHp0ePPzqHOwXhxtvhUFgYJIC406XQxs6x/YQKzhGa6O44aYRBSCMBe3whBlzqOGdQ0PNREMQnn2o1zU6blBemqFyy1QzjyUAmoDMrAuSYHdn2h/RxInYtF8thbMZZfDasmnwnvcCvdVfvGOPPxs8cX84XzhmuBLYuCMtEgGojZfv5dsmuXs9qhF1PDyV5gXV/JCScBcaR30VA4BPbBa5j12c4MB7E6DMWFytA8O9/Z+lQSxeku3dU0qUrQYk1+448ErdVWKxtrIvFr5y6bhB/zi83yK6oA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
