{
 "title": "My Live Temps",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Current Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mylivetemps\")\r\n  |> range(start: -12h)   // last 12 hours to be safe\r\n  |> filter(fn: (r) => r._measurement == \"temperature\")\r\n  |> filter(fn: (r) => r._field == \"fahrenheit\")\r\n  |> filter(fn: (r) => r.location == \"Water In\")\r\n  |> filter(fn: (r) => r.sensorid == \"000000b31eb6\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Water In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"mylivetemps\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"temperature\")\r\n  |> filter(fn: (r) => r._field == \"fahrenheit\")\r\n  |> filter(fn: (r) => r.location == \"Water In\")\r\n  |> filter(fn: (r) => r.sensorid == \"000000b31eb6\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_temperature\")"
    }
   ]
  },
  {
   "title": "Water Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"mylivetemps\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"temperature\")\r\n  |> filter(fn: (r) => r._field == \"fahrenheit\")\r\n  |> filter(fn: (r) => r.location == \"Water Out\")\r\n  |> filter(fn: (r) => r.sensorid == \"000000b285c3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Both Sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"mylivetemps\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"temperature\")\r\n  |> filter(fn: (r) => r._field == \"fahrenheit\")\r\n  |> filter(fn: (r) => r.location == \"Water In\" or r.location == \"Water Out\")\r\n  |> filter(fn: (r) => r.sensorid == \"000000b31eb6\" or r.sensorid == \"000000b285c3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_temperature\")"
    }
   ]
  }
 ]
}